common-obj-y += audio/
common-obj-y += block/ bt/ char/
common-obj-y += ui/
common-obj-y += net/

common-obj-$(CONFIG_LINUX) += fsdev/
extra-obj-$(CONFIG_LINUX) += fsdev/
common-obj-$(CONFIG_SLIRP) += slirp/
