common-obj-y += buffered_file.o migration.o migration-tcp.o
common-obj-$(CONFIG_POSIX) += migration-exec.o migration-unix.o migration-fd.o
common-obj-y += block.o
common-obj-y += page_cache.o

obj-y += savevm.o
